services:
  dev:
    build: .
    working_dir: /html-compose
    volumes:
      - .:/html-compose
    ports:
      - "8080:8080"
    command: >
      gradle jsBrowserDevelopmentRun --no-daemon
        -Dkotlin.js.browser.devserver.port=8080
